{% set name = "yaqc" %}
{% set version = "2023.6.0" %}
{% set sha256 = "7829527c858884445bed75b53e31a0d4360dea1daf1c95306786b71915bfda7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - fastavro >=1.4.0
    - hatchling
  run:
    - python >=3.7
    - fastavro >=1.4.0

test:
  imports:
    - yaqc

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaq-python
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Generic yaq client, written in Python.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
