{% set name = "yaqc" %}
{% set version = "2020.7.3" %}
{% set sha256 = "5500e89a3279b3095bb27363dec069259b02e158819a62a27c39591ca43f7e57" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - fastavro >=0.24.0
    - flit
  run:
    - python >=3.7
    - fastavro >=0.24.0

test:
  imports:
    - yaqc

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaq-python
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Generic yaq client, written in Python.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
